# Generated by Django 6.0.6 on 2026-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLimpiezaCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('filas_originales', models.IntegerField()),
                ('filas_limpias', models.IntegerField()),
                ('separador', models.CharField(default=';', max_length=1)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de limpieza CSV',
                'verbose_name_plural': 'Registros de limpieza CSV',
                'ordering': ['-creado_en'],
            },
        ),
    ]
